# Generated by Django 5.0.7 on 2024-08-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already in use.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.PositiveBigIntegerField(error_messages={'unique': 'This phone number is already in use.'}, unique=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already in use.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='phone_number',
            field=models.PositiveBigIntegerField(error_messages={'unique': 'This phone number is already in use.'}, unique=True),
        ),
    ]
